
-- =============== PART 1: PREPARATION & CREATE ===============

CREATE SCHEMA IF NOT EXISTS concert_hall;
SET search_path TO concert_hall;

-- 1. Venues and concert halls
CREATE TABLE IF NOT EXISTS venues (
    venue_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_name VARCHAR(100) NOT NULL UNIQUE,
    city VARCHAR(60) NOT NULL,
    address VARCHAR(255) NOT NULL
);

-- 2. Ticket categories and pricing policy
CREATE TABLE IF NOT EXISTS ticket_categories (
    category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(50) NOT NULL CONSTRAINT chk_category_name CHECK (category_name IN ('VIP', 'Fan_Zone', 'Standard_Seating', 'Economy')),
    base_price NUMERIC(8, 2) NOT NULL CONSTRAINT chk_base_price CHECK (base_price >= 0),
    service_fee NUMERIC(6, 2) NOT NULL CONSTRAINT chk_service_fee CHECK (service_fee >= 0),
    total_price NUMERIC(8, 2) GENERATED ALWAYS AS (base_price + service_fee) STORED
);

-- 3. Customers (spectators)
CREATE TABLE IF NOT EXISTS customers (
    customer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    registration_date DATE NOT NULL CONSTRAINT chk_reg_date CHECK (registration_date > DATE '2026-01-01')
);

-- 4. Artists and bands
CREATE TABLE IF NOT EXISTS artists (
    artist_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INT UNIQUE, 
    stage_name VARCHAR(100) NOT NULL,
    country_of_origin VARCHAR(60) NOT NULL, 
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id) ON DELETE SET NULL
);

-- 5. Concerts and events
CREATE TABLE IF NOT EXISTS concerts (
    concert_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    venue_id INT NOT NULL,
    concert_date DATE NOT NULL,
    FOREIGN KEY (venue_id) REFERENCES venues(venue_id) ON DELETE CASCADE
);

-- 6. Junction table for artists and concerts (Many-to-Many)
CREATE TABLE IF NOT EXISTS concert_artist (
    concert_id INT NOT NULL,
    artist_id INT NOT NULL,
    performance_order INT DEFAULT 1,
    PRIMARY KEY (concert_id, artist_id),
    FOREIGN KEY (concert_id) REFERENCES concerts(concert_id) ON DELETE CASCADE,
    FOREIGN KEY (artist_id) REFERENCES artists(artist_id) ON DELETE CASCADE
);

-- 7. Hall seats configuration
CREATE TABLE IF NOT EXISTS seats (
    seat_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_id INT NOT NULL,
    row_number INT NOT NULL CONSTRAINT chk_row_num CHECK (row_number > 0),
    seat_number INT NOT NULL CONSTRAINT chk_seat_num CHECK (seat_number > 0),
    is_available BOOLEAN DEFAULT true NOT NULL,
    FOREIGN KEY (venue_id) REFERENCES venues(venue_id) ON DELETE CASCADE
);

-- 8. Purchased tickets
CREATE TABLE IF NOT EXISTS tickets (
    ticket_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INT NOT NULL,
    concert_id INT NOT NULL,
    category_id INT NOT NULL,
    seat_id INT, 
    booking_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id) ON DELETE CASCADE,
    FOREIGN KEY (concert_id) REFERENCES concerts(concert_id) ON DELETE CASCADE,
    FOREIGN KEY (category_id) REFERENCES ticket_categories(category_id) ON DELETE RESTRICT,
    FOREIGN KEY (seat_id) REFERENCES seats(seat_id) ON DELETE SET NULL
);

-- 9. Customer watchlist (saved events)
CREATE TABLE IF NOT EXISTS watchlist (
    customer_id INT NOT NULL,
    concert_id INT NOT NULL,
    added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (customer_id, concert_id),
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id) ON DELETE CASCADE,
    FOREIGN KEY (concert_id) REFERENCES concerts(concert_id) ON DELETE CASCADE
);


-- =============== PART 2: ALTER TABLE ===============

-- 1. Add age restriction flag to filter adult content
ALTER TABLE concerts ADD COLUMN IF NOT EXISTS is_18_plus BOOLEAN DEFAULT false NOT NULL;

-- 2. Expand storage limit to securely fit modern secure password hashes
ALTER TABLE customers ALTER COLUMN password_hash TYPE VARCHAR(512);

-- 3. Prevent booking duplicate events with identical names on the same day at the same venue
ALTER TABLE concerts DROP CONSTRAINT IF EXISTS uq_venue_concert_date;
ALTER TABLE concerts ADD CONSTRAINT uq_venue_concert_date UNIQUE (venue_id, title, concert_date);

-- 4. Set the most common region as default to minimize manual data entry for local bands
ALTER TABLE artists ALTER COLUMN country_of_origin SET DEFAULT 'KZ';

-- 5. Remove redundant performance tracking attribute since lineup order is handled dynamically
ALTER TABLE concert_artist DROP COLUMN IF EXISTS performance_order;


-- =============== PART 3: INSERT ===============

TRUNCATE TABLE customers, artists, venues, concerts, concert_artist, ticket_categories, seats, tickets, watchlist RESTART IDENTITY CASCADE;

-- Venues
INSERT INTO venues (venue_name, city, address) VALUES 
('Infinity Arena', 'Atyrau', 'Abay Qunanbayev Ave, 12'),
('Barys Arena', 'Astana', 'Turangyl St, 5'),
('Central Stadium', 'Almaty', 'Abay Ave, 48'),
('Tokyo Dome', 'Tokyo', '1 Chome-3-61 Koraku'),
('O2 Arena', 'London', 'Peninsula Square, SE10 0DX');

-- Ticket Categories
INSERT INTO ticket_categories (category_name, base_price, service_fee) VALUES 
('Economy', 20.00, 3.00),
('Standard_Seating', 45.00, 5.00),
('Fan_Zone', 85.00, 7.00),
('VIP', 250.00, 20.00);

-- Customers
INSERT INTO customers (full_name, email, password_hash, registration_date) VALUES 
('Elnazar Amanzhan', 'elnazar.o@email.com', 'pbkdf2_sha256_elnazar_2026', '2026-01-15'),
('Nurmuhammed Kuanysh', 'nurmuhammed.b@email.com', 'pbkdf2_sha256_nurmuhammed_2026', '2026-01-20'),
('Adilzhan Serikov', 'adilzhan.s@email.com', 'pbkdf2_sha256_adilzhan_2026', '2026-02-05'),
('Alikhan Salimov', 'alikhan.a@email.com', 'pbkdf2_sha256_alikhan_2026', '2026-02-18'),
('Anuar Kuanysh', 'anuar.q@email.com', 'pbkdf2_sha256_anuar_2026', '2026-03-01'),
('Diyar Kurmanov', 'diyar.k@email.com', 'pbkdf2_sha256_diyar_2026', '2026-03-10'),
('Madiyar Akhmetov', 'madiyar.a@email.com', 'pbkdf2_sha256_madiyar_2026', '2026-03-12'),
('Arman Utepov', 'arman.u@email.com', 'pbkdf2_sha256_arman_2026', '2026-03-15'),
('Sultan Bekov', 'sultan.b@email.com', 'pbkdf2_sha256_sultan_2026', '2026-03-20'),
('Aisulu Muratova', 'aisulu.m@email.com', 'pbkdf2_sha256_aisulu_2026', '2026-03-22'),
('Temporary User', 'temporary.delete@email.com', 'temp_pass_999', '2026-01-05');

-- Artists
INSERT INTO artists (customer_id, stage_name, country_of_origin) VALUES 
((SELECT customer_id FROM customers WHERE email = 'elnazar.o@email.com'), 'Jalanji', 'Kazakhstan'),
(NULL, 'Daft Punk', 'France'),
(NULL, 'Rammstein', 'Germany'),
(NULL, 'Hans Zimmer', 'Germany'),
(NULL, 'Linkin Park', 'USA');

-- Concerts
INSERT INTO concerts (title, venue_id, concert_date) VALUES 
('Cyberpunk Electronic Tour', (SELECT venue_id FROM venues WHERE venue_name = 'Infinity Arena'), '2026-08-12'),
('Symphonic Hollywood Soundtracks', (SELECT venue_id FROM venues WHERE venue_name = 'Barys Arena'), '2026-09-05'),
('Stadium Rock Revival', (SELECT venue_id FROM venues WHERE venue_name = 'Central Stadium'), '2026-09-28'),
('Neon Lights Live', (SELECT venue_id FROM venues WHERE venue_name = 'Tokyo Dome'), '2026-10-15'),
('Industrial Fire Show', (SELECT venue_id FROM venues WHERE venue_name = 'O2 Arena'), '2026-11-20');

-- Seats
INSERT INTO seats (venue_id, row_number, seat_number) VALUES 
((SELECT venue_id FROM venues WHERE venue_name = 'Infinity Arena'), 1, 4),
((SELECT venue_id FROM venues WHERE venue_name = 'Infinity Arena'), 10, 5),
((SELECT venue_id FROM venues WHERE venue_name = 'Barys Arena'), 15, 22),
((SELECT venue_id FROM venues WHERE venue_name = 'Barys Arena'), 15, 23),
((SELECT venue_id FROM venues WHERE venue_name = 'Central Stadium'), 3, 101);

-- Concert Artist
INSERT INTO concert_artist (concert_id, artist_id)
SELECT c.concert_id, a.artist_id 
FROM concerts c, artists a 
WHERE (c.title = 'Cyberpunk Electronic Tour' AND a.stage_name = 'Daft Punk')
   OR (c.title = 'Symphonic Hollywood Soundtracks' AND a.stage_name = 'Hans Zimmer')
   OR (c.title = 'Stadium Rock Revival' AND a.stage_name = 'Linkin Park')
   OR (c.title = 'Neon Lights Live' AND a.stage_name = 'Jalanji')
   OR (c.title = 'Industrial Fire Show' AND a.stage_name = 'Rammstein');

-- Tickets
INSERT INTO tickets (customer_id, concert_id, category_id, seat_id) VALUES 
((SELECT customer_id FROM customers WHERE email = 'anuar.q@email.com'), (SELECT concert_id FROM concerts WHERE title = 'Cyberpunk Electronic Tour'), (SELECT category_id FROM ticket_categories WHERE category_name = 'VIP'), 1),
((SELECT customer_id FROM customers WHERE email = 'elnazar.o@email.com'), (SELECT concert_id FROM concerts WHERE title = 'Stadium Rock Revival'), (SELECT category_id FROM ticket_categories WHERE category_name = 'Standard_Seating'), 5),
((SELECT customer_id FROM customers WHERE email = 'nurmuhammed.b@email.com'), (SELECT concert_id FROM concerts WHERE title = 'Symphonic Hollywood Soundtracks'), (SELECT category_id FROM ticket_categories WHERE category_name = 'Fan_Zone'), NULL),
((SELECT customer_id FROM customers WHERE email = 'diyar.k@email.com'), (SELECT concert_id FROM concerts WHERE title = 'Cyberpunk Electronic Tour'), (SELECT category_id FROM ticket_categories WHERE category_name = 'Economy'), 2),
((SELECT customer_id FROM customers WHERE email = 'madiyar.a@email.com'), (SELECT concert_id FROM concerts WHERE title = 'Neon Lights Live'), (SELECT category_id FROM ticket_categories WHERE category_name = 'Standard_Seating'), 3);

-- Watchlist
INSERT INTO watchlist (customer_id, concert_id) VALUES 
((SELECT customer_id FROM customers WHERE email = 'alikhan.a@email.com'), (SELECT concert_id FROM concerts WHERE title = 'Industrial Fire Show')),
((SELECT customer_id FROM customers WHERE email = 'adilzhan.s@email.com'), (SELECT concert_id FROM concerts WHERE title = 'Neon Lights Live')),
((SELECT customer_id FROM customers WHERE email = 'arman.u@email.com'), (SELECT concert_id FROM concerts WHERE title = 'Stadium Rock Revival')),
((SELECT customer_id FROM customers WHERE email = 'sultan.b@email.com'), (SELECT concert_id FROM concerts WHERE title = 'Cyberpunk Electronic Tour')),
((SELECT customer_id FROM customers WHERE email = 'aisulu.m@email.com'), (SELECT concert_id FROM concerts WHERE title = 'Symphonic Hollywood Soundtracks'));

-- =============== PART 5: GRANT + REVOKE ===============

-- 1. Explicitly revoke privileges to break dependencies before dropping roles
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA concert_hall FROM concert_hall_readonly, concert_hall_writer;
REVOKE ALL PRIVILEGES ON SCHEMA concert_hall FROM concert_hall_readonly, concert_hall_writer;

-- 2. Safe drop now that all object dependencies are cleared
DROP ROLE IF EXISTS concert_hall_readonly;
DROP ROLE IF EXISTS concert_hall_writer;

-- 3. Re-create clean operational system roles
CREATE ROLE concert_hall_readonly;
CREATE ROLE concert_hall_writer;

-- Role Purpose: Grant restricted data viewing capabilities for reporting tools and audit compliance
GRANT USAGE ON SCHEMA concert_hall TO concert_hall_readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA concert_hall TO concert_hall_readonly;

-- Role Purpose: Empower application backends to fully manage the operational dataset and process system workflows
GRANT USAGE ON SCHEMA concert_hall TO concert_hall_writer;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA concert_hall TO concert_hall_writer;

-- =============== PART 4: UPDATE + DELETE ===============

-- UPDATE 1: Complex update statement incorporating a subquery lookup
-- Reason: Shift all shows scheduled at Central Stadium by exactly one month due to regional logistical conflicts
UPDATE concerts
SET concert_date = concert_date + INTERVAL '1 month'
WHERE venue_id = (SELECT venue_id FROM venues WHERE venue_name = 'Central Stadium');

-- UPDATE 2: Basic standalone update statement
-- Reason: Mark the first rows across all venues as unavailable to reserve them for technical sound/video crew equipment
UPDATE seats
SET is_available = false
WHERE row_number = 1;

-- DELETE statement enclosed in a transaction block with RETURNING and ROLLBACK clauses
-- Reason: Safely remove a transient registration record while logging outputs before discarding changes
BEGIN;
DELETE FROM customers 
WHERE email = 'temporary.delete@email.com' 
RETURNING customer_id, full_name, email;
ROLLBACK;